### ISSUE TITLE
cannot process text contains "/"

### ISSUE THREAD

**Issue by chiu0602** [jfet97/ntfm#7]
I use the following code to perform a broadcast. However, if I input broadcast message with "/", for example "please type /help for help.", the broadcast message will not be prompted.
I found that when the input contains "/", the message will be treated as command. At this point, I don't know what is the cause and don't know how can I fix that.

Do anyone can help? Thanks a lot!

```
'use strict';
const { bot, flow } = require('../bot');
const db = require('../db');
const util = require('../util');

bot.onText(/^\/broadcast$/, msg => {
  const chatId = msg.from.id;

  // flow guard
  if(!flow.hasInQueue(chatId)) {
    const isAdminUser = db.isAdminUser(chatId);
    if(!isAdminUser) {
      return;
    }

    bot.sendMessage(chatId, 'Please input broadcast message');

    // after 180 second, the operation will be forcibly cleared
    const timer = setTimeout(flow.clear.bind(flow), 180000, chatId);

    flow.register(
      chatId,
      async data => {
        const msg = data.executeCallData;

        util.notifyRoles(chatId, ['admin', 'poweruser'], '🔔BROADCAST MESSAGE🔔\n🔔PLEASE DO NOT REPLY🔔\n' + msg.text, true, false);

        bot.sendMessage(chatId, 'done');

        clearTimeout(timer);
      },
    );
  } else {
    bot.sendMessage(chatId, 'Unable to execute this command. First complete the previous operation or type /clear.');
  }
});
```

**Comment by chiu0602** [comment]
Terribly sorry that I have copied the example code with eyes closed 🙈
With understanding what the code do and comment out what is not needed, the code work normally.

`
bot.on("message", msg => {

    // if the message is a bot_command or if there are no actions in queue
    // flow.execute() won't be called
    if (!hasEntity("bot_command", msg.entities) && flow.hasInQueue(msg.from.id)) {
        // data sent with each execute call is the msg object
        // so each action will have all the information it might need
        flow.execute(msg.from.id, msg);
    }

    /*
    function hasEntity(entity, entities) {
        if (!entities || !entities.length) {
            return false;
        }
        return entities.some(e => e.type === entity);
    }
    */
});`

This is the best plugin I have ever found. Really thanks @jfet97 !

**Comment by jfet97** [comment]
@chiu0602 I'm glad it's still useful after all this time! I've not been on it for a while, so I'm sorry if I hardly ever answer
